#!/usr/bin/python
import os
import subprocess
import re
import shlex
import sys

key_re = re.compile("^[a-zA-Z_][a-zA-Z0-9_]+$")

try:
    env = subprocess.check_output([".platform.app/env"])
except subprocess.CalledProcessError:
    env = ""

environ = os.environ.copy()
for line in env.split("\n"):
    line = line.strip()
    if line.startswith("#"):
        continue

    try:
        key, value = line.split("=", 1)
    except ValueError:
        continue

    value = " ".join(shlex.split(value))

    if not key_re.match(key):
        continue

    if value != "":
        environ[key] = value
    else:
        environ.pop(key, None)

args = subprocess.list2cmdline(sys.argv[1:])

os.execve(
    "/bin/bash",
    ["/bin/bash", "-c", args,],
    environ,
)
